---
- name: create dirs
  become: true
  ansible.builtin.file:
    path: "{{ nginx_ws.cert_dir }}/{{ item.key }}/"
    state: directory
    recurse: true
    mode: "u=rwx,g=rwx,o=rx"
    owner: "nginx"
    group: "nginx"

- name: "Check if {{item.key}} certs already present"
  become: true
  ansible.builtin.stat:
    path: "{{ nginx_ws.cert_dir }}/{{ item.key }}/privkey.pem"
  register: site_cert_dir

- name: Set altnames
  ansible.builtin.set_fact:
    openssl_altnames: "{{ item.value.altnames | map('regex_replace', '^(.*)$', 'DNS: \\1') | list }}"
  when: item.value.altnames is defined

- name: Set altnames str
  ansible.builtin.set_fact:
    subjectAltName_str: "-addext 'subjectAltName = {{ openssl_altnames | join(', ')}}'"
  when: item.value.altnames is defined

- name: Create self signed certs
  become: true
  ansible.builtin.command: "openssl req -x509 -nodes -days 1 -newkey rsa:2048 -keyout {{ nginx_ws.cert_dir }}/{{ item.key }}/privkey.pem -out {{ nginx_ws.cert_dir }}/{{ item.key }}/fullchain.pem -subj '/C=XX/ST=XX/L=XX/O=XX/OU=XX/CN={{ item.key }}' {{ subjectAltName_str | default('')}}"
  when: not site_cert_dir.stat.exists
