---
- name: restart nginx
  become: true
  ansible.builtin.systemd_service:
    name: "nginx.service"
    state: restarted
    daemon-reload: true
    enabled: true

- name: reload nginx
  become: true
  ansible.builtin.systemd_service:
    name: "nginx.service"
    state: reloaded
    daemon-reload: true
    enabled: true
